//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynergyProga.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int IdEquipment { get; set; }
        public string EqName { get; set; }
        public string EqNumber { get; set; }
        public string EqCost { get; set; }
        public int IdEqType { get; set; }
        public Nullable<int> IdWorkerInfo { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
